#!/bin/sh

if [ ! -e /proc/diskstats ]; then
	exit 0
fi
FIRST=1

echo '{"data":'
echo "\t["
for d in $(cat /proc/diskstats |awk '{print $3}'); do
	if [ $FIRST -ne 1 ]; then
		echo -n ",\n"
	else
		echo ""
		FIRST=0
	fi
	echo -n "\t\t{ \"{#DISK}\" : \"$d\"}"
done
echo "\n\t]"
echo '}'

