#!/bin/sh
if [ -z "$1" ]; then DB="all"; else DB=$1; fi
if [ -z "$2" ]; then TABLE="all"; else TABLE=$2; fi
if [ -z "$3" ]; then DATA="both"; else DATA=$3; fi
case "$DATA" in
	"both"|"")
		SUM="data_length+index_length"
		;;
	"data|index")
		SUM="${DATA}_length"
		;;
	"free")
		SUM="data_free"
		;;
esac
if [ "$DB" != "all" -a -n "$DB" ]; then
	WHERE=" WHERE table_schema='$DB'"
	if [ "$TABLE" != "all" -a -n "$TABLE" ]; then
		ANDTABLE=" AND table_name='$TABLE'"
	fi
fi

SQL="SELECT SUM($SUM) FROM information_schema.tables $WHERE $ANDTABLE"
HOME=/var/lib/zabbix mysql -NBse "$SQL"
