- name: Configure Percona sources.list
  action: template src=percona.list.j2 dest=/etc/apt/sources.list.d/percona.list
  register: repoupdate

- name: Configure Percona repo key
  action: apt_key id=1C4CBDCDCD2EFD2A

- name: Update apt
  action: apt update_cache=yes
  when: repoupdate|changed

- name: Install Percona packages
  action: apt name={{ item }} state=present
  with_items:
    - percona-server-server-5.5
    - percona-server-client-5.5
