---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://ansible.cc/docs/playbooks.html for more information about handlers.

- name: restart ntp
  service: name=ntp state=restarted

- name: restart firewall
  service: name=firewall-cd state=restarted

- name: restart nagios-nrpe-server
  service: name=nagios-nrpe-server state=restarted

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: generate locale
  action: command locale-gen
