#!/bin/bash
### BEGIN INIT INFO
# Provides:          firewall-acs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# required-start:    $network
# required-stop:     $network
# Short-Description: Controla el firewall dels servidors
# Description:       Controla el firewall dels servidors
### END INIT INFO

RESTORE=$(which iptables-restore)
IPTABLES=$(which iptables)

print_state(){
        [ $1 -eq 0 ] && echo -e '\e[70G[   \e[0;32mOK\e[0m   ]' || echo -e '\e[70G[  \e[0;31mFAIL\e[0m  ]'
}
EXIT_STATE=0
set_exit_state(){
        [ $EXIT_STATE -lt $1 ] && EXIT_STATE=$1
}

start(){
	$RESTORE < /etc/acs/iptables.rules
	set_exit_state $?
}

stop(){
        tables="filter nat mangle raw"
        filter="INPUT FORWARD OUTPUT"
        nat="PREROUTING POSTROUTING OUTPUT"
        mangle="PREROUTING INPUT FORWARD OUTPUT POSTROUTING"
        for T in $tables; do
                for C in $(eval echo \$$T); do
                        $IPTABLES -t $T -F $C
                        set_exit_state $?
                        $IPTABLES -t $T -P $C ACCEPT
                        set_exit_state $?
                done
        done
}

case "$1" in
        'start')
                STATUS=$($0 status)
                if [ $? -eq 0 ]; then
                        echo -e "\e[1;31mEl firewall ja esta iniciat\e[0m"
                        set_exit_state 0
                else
                        echo -n "Iniciant firewall..."
                        start
                        print_state $EXIT_STATE
                fi
        ;;
        'stop')
                STATUS=$($0 status)
                if [ $? -ne 0 ]; then
                        echo -e "\e[1;31mEl firewall no esta iniciat\e[0m"
                        set_exit_state 0
                else
                        echo -n "Parant firewall..."
                        stop
                        print_state $EXIT_STATE
                fi
        ;;
        'force-reload')
        ;;
        'restart')
                $0 stop && $0 start
        ;;
        'status')
                echo -n "Estat del firewall..."
                STATUS=$($IPTABLES -L -n -t filter|grep INPUT|grep DROP)
                set_exit_state $?
                print_state $EXIT_STATE
        ;;
        *)
                echo "Usage: $0 { start | stop | restart | force-reload }"
                set_exit_state 1
        ;;
esac

exit $EXIT_STATE
