- name: Install NRPE, snmpd, and common utilities
  apt: name={{ item }} state=present
  with_items:
    - nagios-nrpe-server
    - snmpd
    - sudo
    - bc
    - sysstat
    - gawk
    - nsca
    - smartmontools
    - chkrootkit
    - rkhunter
    - unhide
    - iptables
    - lsb-release
    - perl
    - libnagios-plugin-perl
    - libnet-dns-perl
    - libreadonly-perl
