- name: "Install base packages: php5 php5-mysql libapache2-mod-php5"
  action: apt name={{ item }} state=present
  with_items:
   - php5
   - php5-mysql
   - libapache2-mod-php5
  tags:
   - apt

- name: Install extra php modules
  action: apt name={{ item }} state=present
  with_items: php5_modules_install
  when: php5_modules_install is defined
