- name: Install dovecot dovecot-mysql dovecot-imapd dovecot-pop3d dovecot-sieve dovecot-managesieved
  apt: name={{ item }} state=present
  with_items:
   - dovecot-core
   - dovecot-mysql
   - dovecot-imapd
   - dovecot-pop3d
   - dovecot-sieve
   - dovecot-managesieved

- name: dovecot service state
  service: name=dovecot state=started enabled=yes
