- name: Install backups dependencies
  action: apt name={{ item }} state=present
  with_items:
    - rssh
    - rsync

- name: Configure rssh
  action: lineinfile dest=/etc/rssh.conf regexp='^#allowrsync' line='#allowrsync' backrefs=yes state=present

- name: Backup dir
  action: file src=/var/backups dest=/backup state=link
