- name: Install ntp
  apt: name=ntp state=present update_cache=yes
  tags:
    - apt

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=true
